#############################################################
#                       Data Source                         #
#############################################################
flyway:
  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supply_chain
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    maximumPoolSize: 10
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true

#############################################################
#                       Jackson                             #
#############################################################
  jackson:
    serialization:
      write_dates_as_timestamps: false

